name: dodo_clone
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #MAP
  yandex_mapkit: ^3.2.0

  # Firebase
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.2

  # Localization
  flutter_localizations:
    sdk: flutter

  # My own packages
  address_repository:
    path: packages/address_repository
  dodo_clone_repository:
    path: packages/dodo_clone_repository
  person_repository:
    path: packages/person_repository

  # State manager & Inversion of Control
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  flutter_bloc: ^8.1.1

  # Storage and SQL
  flutter_secure_storage: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Navigation
  auto_route: ^5.0.4

  # Utility & Helpers
  collection:
  equatable: ^2.0.5
  intl: ^0.17.0
  uuid: ^3.0.7
  package_info_plus: ^3.0.2
  flutter_local_notifications: ^12.0.4
  image_picker: ^0.8.6
  permission_handler: ^10.2.0
  photo_manager: ^2.5.1+1
  camera: ^0.10.0+4
  url_launcher: ^6.1.7
  connectivity_plus: ^3.0.2


  # Widgets
  badges: ^2.0.3
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.2.1
  flutter_svg: ^1.1.6
  modal_bottom_sheet: ^2.1.2
  photo_view: ^0.14.0
  carousel_slider: ^4.1.1

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icons/launcher_icon.png"
  image_path_ios: "assets/launcher/icons/ios_launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/bottom_nav_bar_icons/
    - assets/map_icons/
    - assets/images/
    - assets/dodo_images/
    - assets/dodo_images/svg/
    - assets/bottom_nav_bar_icons/
flutter_intl:
  enabled: true
