part of 'mock_data.dart';

final orders = [
  {
    'id': 0,
    'count': 2,
    'total': 579,
    'product_id': 8086,
    'section_id': 1,
    'title': 'Пепперони фреш',
    'description': 'Средняя 40 см, тонкое тесто',
    'image': 'http://kotlyarov.3jz.ru/dodo_clone/images/pepperoni_fresh.png',
    'price': 579,
    'offer_id': 201,
    'crust_id': 0,
    'ingredients_id_list': [],
    'toppings_id_list': [],
  },
  {
    'id': 1,
    'count': 2,
    'total': 579,
    'product_id': 8086,
    'section_id': 1,
    'title': 'Пепперони фреш',
    'description': 'Средняя 40 см, тонкое тесто',
    'image': 'http://kotlyarov.3jz.ru/dodo_clone/images/pepperoni_fresh.png',
    'price': 579,
    'offer_id': 201,
    'crust_id': 0,
    'ingredients_id_list': [],
    'toppings_id_list': [],
  },
  {
    'id': 2,
    'count': 2,
    'total': 579,
    'product_id': 8086,
    'section_id': 1,
    'title': 'Пепперони фреш',
    'description': 'Средняя 40 см, тонкое тесто',
    'image': 'http://kotlyarov.3jz.ru/dodo_clone/images/pepperoni_fresh.png',
    'price': 579,
    'offer_id': 201,
    'crust_id': 0,
    'ingredients_id_list': [],
    'toppings_id_list': [],
  },
  {
    'id': 3,
    'count': 2,
    'total': 579,
    'product_id': 8086,
    'section_id': 1,
    'title': 'Пепперони фреш',
    'description': 'Средняя 40 см, тонкое тесто',
    'image': 'http://kotlyarov.3jz.ru/dodo_clone/images/pepperoni_fresh.png',
    'price': 579,
    'offer_id': 201,
    'crust_id': 0,
    'ingredients_id_list': [],
    'toppings_id_list': [],
  },
  {
    'id': 4,
    'count': 2,
    'total': 579,
    'product_id': 8086,
    'section_id': 1,
    'title': 'Пепперони фреш',
    'description': 'Средняя 40 см, тонкое тесто',
    'image': 'http://kotlyarov.3jz.ru/dodo_clone/images/pepperoni_fresh.png',
    'price': 579,
    'offer_id': 201,
    'crust_id': 0,
    'ingredients_id_list': [],
    'toppings_id_list': [],
  },
  {
    'id': 5,
    'count': 2,
    'total': 579,
    'product_id': 8086,
    'section_id': 1,
    'title': 'Пепперони фреш',
    'description': 'Средняя 40 см, тонкое тесто',
    'image': 'http://kotlyarov.3jz.ru/dodo_clone/images/pepperoni_fresh.png',
    'price': 579,
    'offer_id': 201,
    'crust_id': 0,
    'ingredients_id_list': [],
    'toppings_id_list': [],
  },
  {
    'id': 6,
    'count': 2,
    'total': 579,
    'product_id': 8086,
    'section_id': 1,
    'title': 'Пепперони фреш',
    'description': 'Средняя 40 см, тонкое тесто',
    'image': 'http://kotlyarov.3jz.ru/dodo_clone/images/pepperoni_fresh.png',
    'price': 579,
    'offer_id': 201,
    'crust_id': 0,
    'ingredients_id_list': [],
    'toppings_id_list': [],
  },
  {
    'id': 7,
    'count': 2,
    'total': 579,
    'product_id': 8086,
    'section_id': 1,
    'title': 'Пепперони фреш',
    'description': 'Средняя 40 см, тонкое тесто',
    'image': 'http://kotlyarov.3jz.ru/dodo_clone/images/pepperoni_fresh.png',
    'price': 579,
    'offer_id': 201,
    'crust_id': 0,
    'ingredients_id_list': [],
    'toppings_id_list': [],
  },
  {
    'id': 8,
    'count': 2,
    'total': 579,
    'product_id': 8086,
    'section_id': 1,
    'title': 'Пепперони фреш',
    'description': 'Средняя 40 см, тонкое тесто',
    'image': 'http://kotlyarov.3jz.ru/dodo_clone/images/pepperoni_fresh.png',
    'price': 579,
    'offer_id': 201,
    'crust_id': 0,
    'ingredients_id_list': [],
    'toppings_id_list': [],
  },
  {
    'id': 9,
    'count': 2,
    'total': 579,
    'product_id': 8086,
    'section_id': 1,
    'title': 'Пепперони фреш',
    'description': 'Средняя 40 см, тонкое тесто',
    'image': 'http://kotlyarov.3jz.ru/dodo_clone/images/pepperoni_fresh.png',
    'price': 579,
    'offer_id': 201,
    'crust_id': 0,
    'ingredients_id_list': [],
    'toppings_id_list': [],
  },
  {
    'id': 10,
    'count': 2,
    'total': 579,
    'product_id': 8086,
    'section_id': 1,
    'title': 'Пепперони фреш',
    'description': 'Средняя 40 см, тонкое тесто',
    'image': 'http://kotlyarov.3jz.ru/dodo_clone/images/pepperoni_fresh.png',
    'price': 579,
    'offer_id': 201,
    'crust_id': 0,
    'ingredients_id_list': [],
    'toppings_id_list': [],
  },
];
